services:
  runner:
    build: ./docker/rust
    container_name: runner
    command: cargo watch -x run
    ports:
      - 80:8080
    volumes:
      - ./src:/workspace/src
      - ./tests:/workspace/tests
      - ./templates:/workspace/templates
      - ./statics:/workspace/statics
      - ./migrations:/workspace/migrations
      - ./queries:/workspace/queries
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./Cargo.lock:/workspace/Cargo.lock
      - build-cache:/workspace/target
    env_file:
      - ./default.env
      - ./local.env
    depends_on:
      - database
  tester:
    build: ./docker/rust
    container_name: tester
    command: cargo watch -x test
    volumes:
      - ./src:/workspace/src
      - ./tests:/workspace/tests
      - ./templates:/workspace/templates
      - ./statics:/workspace/statics
      - ./migrations:/workspace/migrations
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./Cargo.lock:/workspace/Cargo.lock
      - ./queries:/workspace/queries
      - build-cache:/workspace/target
    env_file:
      - ./default.env
      - ./local.env
    depends_on:
      - database
  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - database:/workspace/database/volume
    env_file:
      - ./default.env
      - ./local.env

volumes:
  build-cache:
  database:
