services:
  runner:
    build: ./docker/rust
    container_name: runner
    command: cargo watch -x run
    ports:
      - 80:8080
    volumes:
      - ./src:/workspace/src
      - ./tests:/workspace/tests
      - ./templates:/workspace/templates
      - ./statics:/workspace/statics
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./Cargo.lock:/workspace/Cargo.lock
    env_file:
      - ./default.env
      - ./local.env
  tester:
    build: ./docker/rust
    container_name: tester
    command: cargo watch -x test
    volumes:
      - ./src:/workspace/src
      - ./tests:/workspace/tests
      - ./templates:/workspace/templates
      - ./statics:/workspace/statics
      - ./Cargo.toml:/workspace/Cargo.toml
      - ./Cargo.lock:/workspace/Cargo.lock
    env_file:
      - ./default.env
      - ./local.env

volumes:
  build-cache:
