CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(320) UNIQUE
);

CREATE TABLE wallets (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(40) DEFAULT 'default'
);

CREATE TABLE users_wallets (
    user_id integer,
    wallet_id integer,
    PRIMARY KEY (user_id, wallet_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);
