name: Build rust container

on:
  push:
    paths: "**/rust/Dockerfile"
  pull_request:
    paths: "**/rust/Dockerfile"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_container_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push rust
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/rust/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/rust:latest
